haiiliin/pyqtribbon

CHANGE_LOG.md, main.py, ribbon/category.py, ribbon/panel.py
=> Add support to hide panel option button

docs/source/references.rst, main.py, ribbon/__init__.py, ribbon/menu.py, ribbon/toolbutton.py
=> Add support for custom menu for the tool buttons

styles/default.qss
=> Add padding for the Menu

main.py, ribbon/panel.py, ribbon/toolbutton.py
Fix #7 except when the popup mode is MenuButtonPopup, see #14.
=> Change Toolbutton arrow position

main.py, ribbon/tabbar.py
By mistake, the base color of the context category is always red, this PR fixes it.
=> Fix base color of the context category

docs/source/references.rst, docs/source/user.rst, main.py, ribbon/category.py, ribbon/ribbonbar.py, ribbon/tabbar.py, ribbon/titlewidget.py, ribbon/typehints.py
=> Add support for context category with multiple tabs

ribbon/__init__.py, ribbon/category.py, ribbon/panel.py, ribbon/ribbonbar.py, ribbon/toolbutton.py
Add enum instances so that users do not have to add the enum class names when using an enum value
=> Add enum instances in the package

ribbon/ribbonbar.py, ribbon/tabbar.py
Fix bugs of showing multiple contex categories in f9a1d5f5f8fb7b34dd0f52961a567ad2c6e89138.
=> Fix bugs of showing multiple contex categories

ribbon/tabbar.py
Make tab label color symmetrical to its text
=> Make tab label color symmetrical to its text

docs/source/user.rst, main.py, ribbon/ribbonbar.py, ribbon/titlewidget.py
Add support for the file menu.
=> Add support for the file menu

styles/base.qss
Implement mouse enter style for tab bar
=> Implement mouse enter style for tab bar

docs/source/user.rst, main.py, ribbon/category.py, ribbon/panel.py, ribbon/ribbonbar.py
=> Create categories, panels, and widgets using python dictionaries

setup.py
Add base.qss to the styles data
=> Add base.qss to the styles data

ribbon/Qt.py, ribbon/__init__.py, tests/test_categories.py, tests/test_category.py, tests/test_filemenu.py, tests/test_gallery.py, tests/test_panel.py, tests/test_ribbonbar.py, tests/test_use_dictionary_to_create_widgets.py
=> Add tests for basic usage

main.py, ribbon/category.py, ribbon/panel.py, ribbon/ribbonbar.py
Support for setting maximum rows
=> Support for setting maximum rows

docs/source/user.rst, pyqtribbon/ribbonbar.py, pyqtribbon/titlewidget.py
Remove setting tab bar height APIs
=> Remove setting tab bar height APIs

pyqtribbon/panel.py
Fix bugs when the fontsize are floats
=> Fix bugs when the fontsize are floats

pyqtribbon/ribbonbar.py
Update default category color to None
=> Update default category color to None

examples/word.py, pyqtribbon/panel.py, pyqtribbon/ribbonbar.py, pyqtribbon/titlewidget.py
Support fixed height argument when adding widgets to the panel
=> Support fixed height argument when adding widgets to the panel

pyqtribbon/ribbonbar.py
=> Support hiding the ribbon bar automatically

pyqtribbon/category.py
=> Fix category parent constructor called twice

pyqtribbon/__init__.py, pyqtribbon/logger.py, pyqtribbon/titlewidget.py
Fixes #54: remove mouseReleaseEvent and add exception logger
=> Fix title widget events

.github/workflows/pytest.yaml, .github/workflows/test.yml, .github/workflows/tests.yml, requirements/PySide2.txt, requirements/dev.txt, tox.ini
=> Use tox to manage tests

.github/release-drafter.yml, .github/workflows/tests.yml, .gitignore, pyproject.toml, pyqtribbon/titlewidget.py, tests/test_titlewidget.py, tox.ini
=> Test title widget mouse events

tox.ini
=> Remove tox coveralls env

main.py, pyqtribbon/menu.py, pyqtribbon/titlewidget.py, tests/test_categories.py, tests/test_category.py, tests/test_filemenu.py, tests/test_gallery.py, tests/test_main.py, tests/test_panel.py, tests/test_ribbonbar.py, tests/test_titlewidget.py, tests/test_use_dictionary_to_create_widgets.py
=> Fix PySide2 issues on `QActionEvent`

pyqtribbon/panel.py
=> Add `RibbonPanel.addCheckBox` method for adding check boxes

pyqtribbon/titlewidget.py
=> Fix bug when removing quick access and right tool buttons

.github/workflows/publish.yml
xref: https://github.com/pypa/gh-action-pypi-publish/issues/310
=> Bump pypa/gh-action-pypi-publish to v1.12.4
